### ISSUE TITLE
Websocket fallback

### ISSUE THREAD

**Issue by th3noname** [codercom/code-server#256]
Sadly in some cases websocket connections are not possible (eg. corporate proxys). It would be create if a fallback existed.

**Comment by sr229** [comment]
@th3noname this is not possible. Cloud IDEs rely too much on Websockets since they are the implementation of the WebRTC specs. So no, engineering-wise this is impossible to make a fallback just to support such.

Recommending a close as `wontfix`. `code-server` relies on WebRTC and is impossible to support such fallbacks.

**Comment by SuperSandro2000** [comment]
Then ask your IT to enable websockets, use a VPN or ssh proxy.

**Comment by oxodao** [comment]
Cool tips: if you have a VPS/dedicated server you could bind OpenVPN on 443 and add a little line in the config file to check whether the call is for him or for your HTTPS webserver. This lets you go through most proxies without sacrificing your website

**Comment by th3noname** [comment]
@sr229 I expected that answer but wanted to try anyway.

Sadly non of the provided workarounds would work in my case. Tried talking to our CEO and gave up. And all HTTPS connections are intercepted and non HTTP traffic is blocked.

Thanks for the answers!

**Comment by SuperSandro2000** [comment]
So they are doing MITM. I expect in a few years every https website will break due to this and it is a very big security risk if the machine ever gets compromised.

Did you try https over port 80? Did you check ports in the 65ks? Worst case just use your mobile data.
Anyway I am getting way of topic here.

**Comment by kylecarbs** [comment]
@th3noname you can add the `--allow-http` flag to enable http connections.

**Comment by kylecarbs** [comment]
Going to close this as the browser doesn't provide a great alternative.
