### ISSUE TITLE
Add folder to workspace results in grey screen

### ISSUE THREAD

**Issue by Muruloki** [codercom/code-server#309]
- `code-server` version: code-server-1.32.0-310-linux-x64
- OS Version: Ubuntu 16.04.6 LTS

## Description

First of all, thanks a lot for this prioject, it's awesome! :) 

I'm running binary on remote server; when i try to add a folder to the workspace (even if i assign keyboard shortcut) all i see is grey screen; have to edit workspace.json to remove 2nd folder and reload client in the browser to make it work again. Is this a feature or bug? Changing folders using ctrl-k ctrl-o works fine. However using UI it doesn't work.

Some other issues i've noticed: 
- can't install extensions; however it's fine since i can just install then on my local instance and then copy folders over to remote. When trying to install using UI i'm getting this:

Cannot read property 'local' of undefined
Failed to install 'compulim.compulim-vscode-closetag'.

- Markdown preview doesn't work: command 'markdown.showPreviewToSide' not found. However makdown preview enhanced extension works fine so again, not a big deal.

Thanks.

**Comment by nol166** [comment]
@Muruloki it's a bug for sure

**Comment by nol166** [comment]
What version of `compulim.compulim-vscode-closetag` are you using?

**Comment by Muruloki** [comment]
@nol166 oh, that was just random extension; it happens to any of them. For example just tried Angular 7 Snippets - TypeScript, Html, Angular Material, i think it's v7.2.5

Cannot read property 'local' of undefined
Failed to install 'mikael.angular-beastcode'.

I'm using UI to install. If i try to use extensions: isntall from file it will complain about improper tar format or something like that. Reading other comments here it looks i have to install bsd tar since gnutar has some issues unpacking the vscode extensions but again, i didn't try to do that since there is a relatively easy workaround.

**Comment by foresthoffman** [comment]
Hello @Muruloki, there is a pending PR (https://github.com/codercom/code-server/pull/245) which will fix the bug prohibiting installation from VSIX. The difference between bsdtar and gnutar shouldn't matter. The problem was the assumption that the VSIX is in TAR format rather than the standard ZIP.

Extensions:
- [compulim.compulim-vscode-closetag](https://marketplace.visualstudio.com/items?itemName=Compulim.compulim-vscode-closetag) should be working just fine
- [mikael.angular-beastcode](https://marketplace.visualstudio.com/items?itemName=mikael.angular-beastcode) should also be working just fine, 7.2.4 is provided

It's unusal that the `markdown.showPreviewToSide` command isn't working, since the extension default is included under `lib/vscode-default-extensions/extensions/markdown-language-features`, but i'm seeing the unregistered command error as well. Good to hear that there is an alternative.

Thanks,
Forest

**Comment by Muruloki** [comment]
@foresthoffman Great, thank you. 

What about adding folder to workspace, do you know why it's resulting in blank grey screen? :)

**Comment by foresthoffman** [comment]
I'm not certain as to the root of the issue, but I do receive the following error:
``` ERROR  Failed "Start workbench" duration=1002ms
13:04:28.756 main.js?f92d:1 duration (i): i {expected: 1000, ms: 1553191467376}
13:04:28.757 main.js?f92d:1 error (Error): Error: [UriError]: Scheme contains illegal characters.
    at _validateUri (uri.ts?336c:38)
    at _URI.URI (uri.ts?336c:175)
    at new _URI (uri.ts?336c:391)
    at Function.URI.revive (uri.ts?336c:367)
    at Object.reviveWorkspaceIdentifier (workspaces.ts?067d:38)
    at CodeRendererMain.reviveUris (main.ts?bd53:89)
    at CodeRendererMain.init (main.ts?bd53:70)
    at new CodeRendererMain (main.ts?bd53:61)
    at main (main.ts?bd53:331)
    at Workbench.eval (workbench.ts?f527:192)```

The issue appears to be coming from `lib/vscode/src/vs/base/common/uri.ts`, which is odd.

You can recover from the failed workspace load, by clearing your cache.

**Comment by nol166** [comment]
You can also delete `workspace` entry from local storage until the actual issue is fixed.

**Comment by foresthoffman** [comment]
Should be fixed by https://github.com/codercom/code-server/pull/317.
