### ISSUE TITLE
Open dialog cuts off some files

### ISSUE THREAD

**Issue by nol166** [codercom/code-server#336]
- `code-server` version: running directly from repo, latest pull
- OS Version: macOS

## Description
The open dialog seems to cut off the filename at the end of the list

## Steps to Reproduce
1. Click `file - open workspace`
2. Select a folder with a lot of files/directories
3. See cutoff at the bottom

## Screenshot
![Screen Shot 2019-03-25 at 4 29 43 PM](https://user-images.githubusercontent.com/5651438/54955562-aad04d00-4f1b-11e9-9f04-1e6e046c02a3.png)

**Comment by nol166** [comment]
moved to frontend repo

**Comment by cathook** [comment]
I encountered the same issue too. After a bit survey, I think the root cause is that in [packages/vscode/src/dailog.ts](https://github.com/cdr/code-server/blob/master/packages/vscode/src/dialog.ts),`Dailog` class asks the UI widget to resolve the height of the scroll-able area at the wrong time. When it calls `this.entryList.layout()` at [line 318](https://github.com/cdr/code-server/blob/master/packages/vscode/src/dialog.ts#L318), `path` is still empty so the height of the corresponding element is zero. After `path` is resolved, the element height becomes 28px and the height of the scroll-able area becomes 28px smaller, which is misaligned with the state the UI widget recorded.

One simple solution is to move [line 318](https://github.com/cdr/code-server/blob/master/packages/vscode/src/dialog.ts#L318) to [line 393](https://github.com/cdr/code-server/blob/master/packages/vscode/src/dialog.ts#L393) where `path` is just assigned. Not sure if there's better way.

Also, just curious, what's the frontend repo?

**Comment by code-asher** [comment]
Thanks for the excellent diagnosis! I've just committed the fix.

Our `frontend` repository holds the `coder.com` website; I think this may have been mistakenly moved there.
