### ISSUE TITLE
recommendations for disabling features: Terminal, Debugger, Marketplace

### ISSUE THREAD

**Issue by bolek-wisniewski** [codercom/code-server#381]
## Description
My organization would like to host a couple of these web ide servers, but have raised concerns around security. Is there any way to disable some of the more potent features of vscode, such as terminal, debugger, marketplace? Do you have any recommendations on how to approach this problem?

**Comment by Multishifties** [comment]
I'm digging through the VSCode docs now, and I'm not seeing anything that would allow that at a quick glance.

Has your team considered setting up the code-server instances to be run as limited permission users? I believe you might be able to manage the permissions in such a way where users would be unable to access a lot of things in the terminal, as well as render them unable to download additional extensions.

**Comment by bolek-wisniewski** [comment]
Thanks for the quick response and thanks for checking!

Indeed, we're going to restrict user permissions, outbound connections, as well as limiting instance cpu / ram. 

Ideally, we would like to disable the user interaction with these components in the front end as well. Looks like it might be a long hard journey though :)

**Comment by schrej** [comment]
Maybe running it in separate docker containers would be a good option? If you build a custom docker image without a shell, access would be very limited, probably.
That would also facilitate limiting cpu and ram.

**Comment by pmansour** [comment]
I don't think this issue is wholly solved by running the VS Code server in a separate container. For one, if we'd like the code server to run using HTTPS, we need the code-server launcher to have access to a valid SSL certificate. Even if the VS code server runs on a container that has no other valuable data, the certificate itself allows an attacker to impersonate this server and cause much more damage.

I would love to see either the ability to disable the terminal, or for the terminal to run as a different (more restricted) user than the one that launched code-server, and that doesn't even have access to that cert. Alternatively, allowing the terminal to re-authenticate the user would be useful too.

**Comment by fbartels** [comment]
> if we'd like the code server to run using HTTPS, we need the code-server launcher to have access to a valid SSL certificate. Even if the VS code server runs on a container that has no other valuable data, the certificate itself allows an attacker to impersonate this server and cause much more damage

Just do ssl termination in a reverse proxy

**Comment by pmansour** [comment]
@fbartels A termination proxy is a good suggestion (which I'm going to try on my personal cloud VM), but I don't think that takes away from the feature request.

I would love to see code-server as a simple secure-by-default binary that you can run on your machine, rather than a tool that gives remote execution capabilities and requires installation and configuration of another web server to work securely.
