### ISSUE TITLE
Add ENV PORT handling

### ISSUE THREAD

**Issue by domesticmouse** [codercom/code-server#527]
I'm looking at whether I can run this atop Google [Cloud Run](https://cloud.google.com/run/), AKA [Knative](https://cloud.google.com/knative/), which is a way of running serverless style Docker images inside of [Kubernetes Engine](https://cloud.google.com/kubernetes-engine/).

My first requirement is to honor a `PORT` environment variable which defines where we should bind. Can I get some direction on what I need to patch to make that happen? Thanks!

**Comment by lucacasonato** [comment]
The PORT env var was added in release 1.854-vsc1.33.1 (https://github.com/codercom/code-server/releases/tag/1.854-vsc1.33.1).

To make this work well on GCR you will have to do some work. If you run the container the way it is now you will lose all of your config, extensions and work every so often because Google scales down to 0 instances when you are not using the container. Because GCR expects a container to be stateless you will get a fresh instance with none of your previous work. To make this work you would have to make your container persist state, so for example connect your container to a Cloud Storage instance to make it persist data there. AFAIK Google does not have support for that natively in Cloud Run. I am interested in this too and will do some research. If I find anything interesting ill make sure to post it in this issue.

**Comment by domesticmouse** [comment]
Thank you for the clarification. I’d love some documentation on how this is built so we can adapt it for using atop GKE. Thanks!
