### ISSUE TITLE
prevent ctrl+w from closing tab

### ISSUE THREAD

**Issue by 0xfd000000** [codercom/code-server#53]
I guess it's not possible to catch the ctrl+w shortcut before the browser interprets it, but would it be possible to show a "leave this page?" confirmation dialog to prevent the good old muscle memory from screwing up ones work?

**Comment by kylecarbs** [comment]
Will definitely add this!

**Comment by odiak** [comment]
Can you use Ctrl + W to close editor tabs or some other VSCode functions?
And I think it's better to close browser tab (maybe with confirmation) if any editor tabs are opened.

**Comment by jeasonstudio** [comment]
Hotkey should be consistent with `VSCode` to get an immersive experience.

**Comment by avelino** [comment]
> Will definitely add this!

Important to have a page in the documentation listing all the default code-server shortcuts

**Comment by gijo-varghese** [comment]
Right now when I press `Ctrl + W` it closes the browser tab, instead of closing the file. Since I used to close files using this in real VS Code, we need to find a solution for this

**Comment by gijo-varghese** [comment]
we could use something like 
```javascript
window.onbeforeunload = function (e) {
    // Cancel the event
    e.preventDefault();

    // Chrome requires returnValue to be set
    e.returnValue = 'Really want to quit the game?';
};
```

It doesn't prevent from closing, but at least show you an additional confirmation

**Comment by code-asher** [comment]
Fixed with https://github.com/codercom/code-server/pull/463.

**Comment by MicroDroid** [comment]
It totally closes the tab for me.

Chrome: Version 80.0.3962.2 (Official Build) dev (64-bit)
Code Server: 2.1692-vsc1.39.2

**Comment by MicroDroid** [comment]
It totally closes the tab for me.

Chrome: Version 80.0.3962.2 (Official Build) dev (64-bit)
Code Server: 2.1692-vsc1.39.2

**Comment by MicroDroid** [comment]
I didn't unassign anyone :thinking:

**Comment by sr229** [comment]
@MicroDroid unfortunately we can't solve this - I believe this is also persistent in upstream VSCode so this is more of a by-design since you can't override Ctrl-W as far as I investigated.

**Comment by MicroDroid** [comment]
Perhaps we can at least show a confirmation dialog?

**Comment by sr229** [comment]
I think we did that over in Theia, not sure how we want it on VSCode though.

Feel free to bring this up to Microsoft as well.

CC @code-asher what do you think?

**Comment by code-asher** [comment]
Hmm we used to do this but then it kept popping up when it wasn't needed like when using full-screen or an app window. If there's a way to distinguish between those states then we could put it back in. But maybe it'd be more proper for the change to be made upstream.

**Comment by MicroDroid** [comment]
The `beforeunload` should do it.

**Comment by code-asher** [comment]
The problem we ran into was that if you run something like this:

```
chrome --app=http://my.ide.com
```

Then `ctrl+w` works as expected so we don't need `beforeunload`. But then when you try to close the application the `beforeunload` prevents you from doing so and forces you to confirm which users reported as jarring.

So we'd just need a way to detect if code-server is running in an app window (or full-screen because it should have the same behavior) and in that case elect *not* to prevent the window close.

**Comment by A-312** [comment]
> ```js
> window.onbeforeunload = function (e) {
>     // Cancel the event
>     e.preventDefault();
> ```

You can't do that^^'. Disable the shortcut on keyup keydown keypress

**Comment by tooyangtoonaive** [comment]
If you use firefox, you can modify omni.ja to forbid ctrl w t n by following link
[https://www.math.cmu.edu/~gautam/sj/blog/20220329-firefox-disable-ctrl-w.html](url)

**Comment by jonahgraham** [comment]
> If you use firefox, you can modify omni.ja to forbid ctrl w t n by following link [https://www.math.cmu.edu/~gautam/sj/blog/20220329-firefox-disable-ctrl-w.html](url)

Clickable link is: <https://www.math.cmu.edu/~gautam/sj/blog/20220329-firefox-disable-ctrl-w.html>


<details><summary>Details for why the quoted comment doesn't have a clickable link</summary>
<p>



The correct link is shown, but it is not what is linked to if you click it.

This is because the markdown used is:

```markdown
[https://www.math.cmu.edu/~gautam/sj/blog/20220329-firefox-disable-ctrl-w.html](url)
```

Which means the URL that browser will send to is `url` relative to this page, e.g. <https://github.com/coder/code-server/issues/url>

It should be either:

```markdown
<https://www.math.cmu.edu/~gautam/sj/blog/20220329-firefox-disable-ctrl-w.html>
```

or perhaps with a descriptive link text

```markdown
[blog post](https://www.math.cmu.edu/~gautam/sj/blog/20220329-firefox-disable-ctrl-w.html)
```

Feel free to delete this comment once above one is cleaned up.


</p>
</details>
