### ISSUE TITLE
Detect archive type of extension to decompress

### ISSUE THREAD

**Issue by kylecarbs** [codercom/code-server#92]
We've filled the client zip implementation with tar so we can eventually load extensions on the client. Installing from a VSIX no longer works because the standard format is a zip.

We should detect the archive type then use the appropriate fill.

**Comment by RiFi2k** [comment]
Not sure what the limitations are here but is using the CLI an option?

https://code.visualstudio.com/docs/editor/command-line

**Comment by foresthoffman** [comment]
Howdy @RiFi2k, this isn't related to the current issue, but thank you for the suggestion. The reason we're not using the official [VS Code Marketplace](https://marketplace.visualstudio.com/vscode) is because it is a restriction in their TOS. See the following comment from one of our CTO's: https://github.com/codercom/code-server/issues/30#issuecomment-470180565.
